version: '3.5'

services:

  # Django
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver" ,"0.0.0.0:80"]
    #command: ["python", "manage.py", "mineNewBlock"]
    volumes:
      - ./blockchainNode/:/app/blockchainNode
    working_dir: /app/blockchainNode
    ports:
      - "4000:80"
    expose:
      - "80"

  # Rabbit MQ
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    working_dir: /app
    ports:
      - "5672:5672"
      - "15672:15672"

  # Celery
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "nodeProject", "worker", "--loglevel=info"]
    volumes:
      - ./blockchainNode/:/app/blockchainNode
    working_dir: /app/blockchainNode
    depends_on:
      - rabbit
      - django
