version: '3.5'

services:

  # Rabbit MQ
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  # Django
  django:
    build:
      context: .
      dockerfile: Dockerfile
    #command: ./nodeProject/scripts/atualizarBanco.sh
    command: ./nodeProject/scripts/rodarServidorLAN.sh
    volumes:
      - ./nodesAuxiliares/node$NUMBER/blockchainNode/:/app/blockchainNode
    working_dir: /app/blockchainNode
    ports:
      - "$PORT:80"
    expose:
      - "80"
    depends_on:
      - rabbit

  # Celery - Worker
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "nodeProject", "worker", "--loglevel=info"]
    volumes:
      - ./nodesAuxiliares/node$NUMBER/blockchainNode/:/app/blockchainNode
    working_dir: /app/blockchainNode
    depends_on:
      - django

  # Celery - Beat Scheduler
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "nodeProject", "beat", "--loglevel=info"]
    volumes:
      - ./nodesAuxiliares/node$NUMBER/blockchainNode/:/app/blockchainNode
    working_dir: /app/blockchainNode
    depends_on:
      - celery-worker
