# Generated by Django 2.1.8 on 2019-04-01 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('votes', models.TextField()),
                ('difficulty', models.PositiveIntegerField()),
                ('nonce', models.BigIntegerField(default=-1)),
                ('previousBlockHash', models.CharField(max_length=512)),
                ('currentBlockHash', models.CharField(default='1111111111111111111111111111111111111111111111111111111111111111', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('port', models.PositiveIntegerField()),
                ('host', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterPubKey', models.CharField(max_length=500)),
                ('candidateRole', models.CharField(choices=[('Presidente', 'Presidente'), ('Senador', 'Senador'), ('Governador', 'Governador'), ('Prefeito', 'Prefeito')], max_length=30)),
                ('candidateNumber', models.PositiveIntegerField()),
                ('digitalSignature', models.CharField(max_length=100)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nodeApp.Block')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
