# Generated by Django 2.1.7 on 2019-03-27 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('votes', models.TextField()),
                ('difficulty', models.PositiveIntegerField()),
                ('nonce', models.PositiveIntegerField()),
                ('previousBlockHash', models.CharField(max_length=512)),
                ('currentBlockHash', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterPubKey', models.CharField(max_length=500)),
                ('candidateRole', models.CharField(choices=[('PDT', 'Presidente'), ('SEN', 'Senador'), ('GOV', 'Governador'), ('PRF', 'Prefeito')], max_length=30)),
                ('candidateNumber', models.PositiveIntegerField()),
                ('digitalSignature', models.CharField(max_length=100)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nodeApp.Block')),
            ],
        ),
    ]
