# Generated by Django 2.1.7 on 2019-02-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='hash',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
