# Generated by Django 2.1.7 on 2019-02-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainApp', '0002_block_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='block',
            name='previousHash',
            field=models.CharField(max_length=64),
        ),
    ]
