# Generated by Django 2.1.7 on 2019-02-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainApp', '0003_auto_20190219_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
