# Generated by Django 2.1.7 on 2019-02-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainApp', '0005_blockchain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('rg', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=11)),
                ('tituloEleitor', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('publicKey', models.CharField(max_length=5)),
                ('privateKey', models.CharField(max_length=5)),
                ('amigos', models.ManyToManyField(to='blockchainApp.Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Blockchain',
        ),
    ]
