# Generated by Django 2.1.7 on 2019-02-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainApp', '0007_auto_20190228_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='amigos',
            field=models.ManyToManyField(blank=True, to='blockchainApp.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='privateKey',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='publicKey',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tituloEleitor',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
